import { Table } from "ts-sql-query/Table";
import { DBConnection } from "./connection";

// ─── Database Definitions ──────────────────────────────────────────────── ✣ ─

class TEmote extends Table<DBConnection, "TEmote"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  name = this.column("name", "string");
  discordId = this.column("discord_id", "string");
  image = this.column("image", "string");

  constructor() {
    super("emote");
  }
}

export const tEmote = new TEmote();

class TVariant extends Table<DBConnection, "TVariant"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  name = this.column("name", "string");

  constructor() {
    super("variant");
  }
}

export const tVariant = new TVariant();

class TEmoteVariant extends Table<DBConnection, "TEmoteVariant"> {
  emoteId = this.column("emote_id", "int");
  variantId = this.column("variant_id", "int");
  image = this.column("image", "string");

  constructor() {
    super("emote_variant");
  }
}

export const tEmoteVariant = new TEmoteVariant();
